- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"
- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"
- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"
- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"
- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"
- name: "question"
  color: "d876e3"
  description: "Further information is requested"
- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"
- name: "backend"
  color: "0e8a16"
  description: "Related to backend code"
- name: "frontend"
  color: "1d76db"
  description: "Related to frontend code"
- name: "mobile"
  color: "fbca04"
  description: "Related to mobile app"
- name: "uk-compliance"
  color: "5319e7"
  description: "Related to UK compliance requirements"
- name: "security"
  color: "ee0701"
  description: "Security related issue"
- name: "performance"
  color: "b11f1f"
  description: "Performance improvement"
- name: "testing"
  color: "02d7e1"
  description: "Related to testing"
- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"
- name: "critical"
  color: "b60205"
  description: "Critical issue requiring immediate attention"
- name: "high-priority"
  color: "d93f0b"
  description: "High priority issue"
- name: "medium-priority"
  color: "f9a115"
  description: "Medium priority issue"
- name: "low-priority"
  color: "0e8a16"
  description: "Low priority issue"
- name: "bs5839"
  color: "0052cc"
  description: "Related to BS5839 fire alarm standards"
- name: "vat"
  color: "a2eeef"
  description: "Related to UK VAT calculations"
- name: "scheduling"
  color: "d4c5f9"
  description: "Related to engineer scheduling"
- name: "financial"
  color: "006b75"
  description: "Related to financial features"
