name-template: 'v$RESOLVED_VERSION ðŸŒŸ'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

categories:
  - title: 'ðŸš€ New Features'
    labels:
      - 'enhancement'
      - 'feature'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: 'ðŸ”’ Security Updates'
    labels:
      - 'security'
  - title: 'ðŸ“š Documentation'
    labels:
      - 'documentation'
  - title: 'ðŸ‡¬ðŸ‡§ UK Compliance Updates'
    labels:
      - 'uk-compliance'
      - 'bs5839'
      - 'vat'
  - title: 'ðŸ§¹ Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: 'ðŸš¨ Breaking Changes'
    labels:
      - 'breaking-change'

template: |
  ## What's Changed

  $CHANGES

  ## UK Compliance Notes
  This release includes updates to:
  - BS5839 certificate generation
  - UK VAT calculations
  - Compliance documentation

  **Full Changelog**: https://github.com/firelinksystem/firelink-system/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
